apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
      - image: darumatic/locustio:20180510-1711
        name: locust
        env:
          - name: LOCUST_MODE
            value: master
          - name: TARGET_HOST
            value: http://10.20.14.247:30048
        ports:
          - name: loc-master-web
            containerPort: 8089
            protocol: TCP
          - name: loc-master-p1
            containerPort: 5557
            protocol: TCP
          - name: loc-master-p2
            containerPort: 5558
            protocol: TCP
        resources:
          requests:
            memory: "256M"
            cpu: "0.05"
          limits:
            memory: "0.5Gi"
            cpu: "0.5"



