apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-master
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
      - image: darumatic/locustio:20180510-2100
        name: locust
        env:
          - name: LOCUST_MODE
            value: master
          - name: TARGET_HOST
            value: http://10.20.14.247:32760
        ports:
          - name: loc-master-web
            containerPort: 8089
            protocol: TCP
          - name: loc-master-p1
            containerPort: 5557
            protocol: TCP
          - name: loc-master-p2
            containerPort: 5558
            protocol: TCP
        resources:
          requests:
            memory: "32M"
            cpu: "0.05"
          limits:
            memory: "128M"
            cpu: "0.5"
        volumeMounts:
        - mountPath: /locust-tasks/tasks.py
          subPath: tasks.py
          name: tasks
      volumes:
      - name: tasks
        configMap:
          name: tasks
          items:
          - key: tasks.py
            path: tasks.py






